#! /bin/bash

SESSION="efall-llpc1"
export DISPLAY=:0

openSession () {
    echo "Create new ease-fmri-avatar-lablink session"
    
    # create windows 
    tmux new-session -d -s $SESSION
    tmux split-window -h -t $SESSION:0.0
    tmux split-window -v -t $SESSION:0.1
    tmux split-window -v -t $SESSION:0.0
    
    # enter venvs
    tmux send-keys -t $SESSION:0.0 "source ../activate" Enter
    tmux send-keys -t $SESSION:0.1 "source ../activate   " Enter
    tmux send-keys -t $SESSION:0.2 "source ../activate" Enter
    tmux send-keys -t $SESSION:0.3 "source ../activate   " Enter

    # clear screen
    #tmux send-keys -t $SESSION:0.0 "clear" Enter
    #tmux send-keys -t $SESSION:0.1 "clear" Enter
    #tmux send-keys -t $SESSION:0.2 "clear" Enter
    #tmux send-keys -t $SESSION:0.3 "clear" Enter
 

    # start services
    # tmux send-keys -t $SESSION:0.2 "labc serve TriggerAndButtons" Enter
    # tmux send-keys -t $SESSION:0.2 "ipython" Enter
    echo "Wait 5 senconds before starting StreamViewer"
    sleep 5 # just a savety to not get into racing conditions
    #tmux send-keys -t $SESSION:0.0 "export DISPLAY=:0 && labc serve StreamViewer" Enter
    tmux send-keys -t $SESSION:0.0 "labc serve StreamViewer" Enter

    #tmux send-keys -t $SESSION:0.3 "labc serve SoundService" Enter
    #tmux send-keys -t $SESSION:0.1 "./test_stream" Enter
}

if [ -z "$1" ]; then
    CMD="open" 
else
    CMD=$1
fi

if [ "$CMD" = "kill" ]; then
    echo "killing session" $SESSION
    tmux kill-session -t $SESSION
else
    tmux has-session -t $SESSION 2>/dev/null
    if [ $? != 0 ]; then
        openSession
    fi
    tmux attach-session -t $SESSION
fi
